title = "TOML Example"
service_host = "toml_host"
log_level = "info"
feature_x_enabled = true

[owner]
name = "Tom Preston-Werner"
dob = "1979-05-27T07:32:00-08:00" # Represent as string for simplicity in Lua table comparison

[database]
enabled = true
ports = [ 8000, 8001, 8002 ]
data = [ ["delta", "phi"], [3.14] ]
temp_targets = { cpu = 79.5, case = 72.0 }
